const KEY='tnm-data-v1';
const seed={products:[{id:1,sku:'SP001',name:'Áo thun Basic',cat:'Thời trang',price:120000,cost:65000,stock:35,min:5},{id:2,sku:'SP002',name:'Quần jean Classic',cat:'Thời trang',price:320000,cost:190000,stock:12,min:5},{id:3,sku:'SP003',name:'Tai nghe Bluetooth',cat:'Điện tử',price:450000,cost:280000,stock:7,min:3},{id:4,sku:'SP004',name:'Bình nước 750ml',cat:'Gia dụng',price:95000,cost:48000,stock:28,min:5},{id:5,sku:'SP005',name:'Sạc nhanh 20W',cat:'Điện tử',price:220000,cost:125000,stock:3,min:5}],customers:[{id:1,name:'Nguyễn Văn An',phone:'0901234567',address:'Hà Nội',debt:0},{id:2,name:'Trần Minh Anh',phone:'0912345678',address:'Ninh Bình',debt:150000}],suppliers:[{id:1,name:'Nhà cung cấp ABC',phone:'0988888888',address:'Hà Nội'}],orders:[{id:1001,customer:'Nguyễn Văn An',total:770000,status:'Hoàn thành',payment:'Chuyển khoản',date:'2026-10-05',items:[{productId:1,qty:2,price:120000},{productId:2,qty:1,price:320000}]},{id:1002,customer:'Trần Minh Anh',total:450000,status:'Đang giao',payment:'COD',date:'2026-10-05',items:[{productId:3,qty:1,price:450000}]}],expenses:[{id:1,type:'Vận chuyển',amount:30000,date:'2026-10-05',note:'Giao hàng'}],debts:[]};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(seed); let page='dashboard', modal=null, cart=[];
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n)||0);
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const sum=a=>a.reduce((x,y)=>x+Number(y||0),0);
function revenue(){return sum(db.orders.filter(o=>o.status!=='Đã hủy').map(o=>o.total))}
function cost(){return sum(db.orders.flatMap(o=>o.items||[]).map(i=>(db.products.find(p=>p.id==i.productId)?.cost||0)*i.qty))}
function nav(){return [{id:'dashboard',i:'▦',t:'Tổng quan'},{id:'pos',i:'＋',t:'Bán hàng / POS'},{id:'orders',i:'▤',t:'Đơn hàng'},{id:'products',i:'◈',t:'Sản phẩm'},{id:'inventory',i:'▣',t:'Kho hàng'},{id:'customers',i:'♙',t:'Khách hàng'},{id:'suppliers',i:'⌂',t:'Nhà cung cấp'},{id:'purchases',i:'⇩',t:'Nhập hàng'},{id:'expenses',i:'◫',t:'Chi phí'},{id:'reports',i:'◒',t:'Báo cáo'},{id:'debts',i:'₫',t:'Công nợ'},{id:'settings',i:'⚙',t:'Cài đặt'}]}
function layout(){document.getElementById('app').innerHTML='<div class="app"><aside class="sidebar"><div class="brand">TNM<small>SALES MANAGER</small></div><div class="nav">'+nav().map(n=>'<button class="'+(page===n.id?'active':'')+'" onclick="go(\''+n.id+'\')"><span>'+n.i+'</span>'+n.t+'</button>').join('')+'</div></aside><main class="main"><header class="top"><h1>'+nav().find(n=>n.id===page)?.t+'</h1><div class="actions"><button class="btn" onclick="toggleTheme()">◐</button><button class="btn primary" onclick="go(\'pos\')">+ Bán hàng</button></div></header><section class="content">'+render()+'</section></main><nav class="mobile-nav">'+nav().slice(0,5).map(n=>'<button class="'+(page===n.id?'active':'')+'" onclick="go(\''+n.id+'\')">'+n.i+'<br>'+n.t.split(' /')[0]+'</button>').join('')+'</nav></div>'+ (modal?renderModal():'');}
function go(p){page=p;modal=null;layout()}
function dashboard(){let rev=revenue(), c=cost(), exp=sum(db.expenses.map(e=>e.amount));return '<div class="grid stats"><div class="card"><div class="stat-label">Doanh thu</div><div class="stat-value">'+money(rev)+'</div></div><div class="card"><div class="stat-label">Lợi nhuận ước tính</div><div class="stat-value">'+money(rev-c-exp)+'</div></div><div class="card"><div class="stat-label">Đơn hàng</div><div class="stat-value">'+db.orders.length+'</div></div><div class="card"><div class="stat-label">Giá trị tồn kho</div><div class="stat-value">'+money(sum(db.products.map(p=>p.stock*p.cost)))+'</div></div></div><div class="grid cards" style="margin-top:16px"><div class="card"><h3>Doanh thu 7 ngày</h3><div class="chart">'+[62,80,45,90,72,100,88].map((v,i)=>'<div class="bar" style="height:'+v*1.7+'px"><i>'+money(Math.round(rev*v/535))+'</i><span>T'+(i+1)+'</span></div>').join('')+'</div></div><div class="card"><h3>Cảnh báo tồn kho</h3>'+db.products.filter(p=>p.stock<=p.min).map(p=>'<p>⚠️ <b>'+esc(p.name)+'</b><br><span class="muted">Còn '+p.stock+' sản phẩm</span></p>').join('')||'<div class="empty">Kho đang ổn định</div>'+'</div><div class="card"><h3>Đơn gần đây</h3>'+db.orders.slice(-5).reverse().map(o=>'<p><b>#'+o.id+'</b> · '+money(o.total)+'<br><span class="badge '+(o.status==='Hoàn thành'?'green':'amber')+'">'+o.status+'</span></p>').join('')+'</div></div>'}
function tablePage(type){let data=db[type];let title={products:'Sản phẩm',customers:'Khách hàng',suppliers:'Nhà cung cấp',orders:'Đơn hàng',expenses:'Chi phí'}[type];let search=window._q||'';let filtered=data.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));let cols=type==='products'?['SKU','Tên sản phẩm','Danh mục','Giá bán','Giá vốn','Tồn']:type==='customers'?['Tên','Điện thoại','Địa chỉ','Công nợ']:type==='suppliers'?['Nhà cung cấp','Điện thoại','Địa chỉ']:type==='expenses'?['Loại','Số tiền','Ngày','Ghi chú']:['Mã đơn','Khách hàng','Tổng tiền','Thanh toán','Trạng thái','Ngày'];let rows=filtered.map(x=>type==='products'?[x.sku,x.name,x.cat,money(x.price),money(x.cost),'<span class="badge '+(x.stock<=x.min?'red':'green')+'">'+x.stock+'</span>']:type==='customers'?[x.name,x.phone,x.address,money(x.debt)]:type==='suppliers'?[x.name,x.phone,x.address]:type==='expenses'?[x.type,money(x.amount),x.date,x.note]:['#'+x.id,x.customer,money(x.total),x.payment,'<span class="badge">'+x.status+'</span>',x.date]);return '<div class="toolbar"><div class="left"><input class="input" placeholder="Tìm kiếm..." value="'+esc(search)+'" oninput="window._q=this.value;renderRefresh()"></div><div class="right"><button class="btn primary" onclick="openAdd(\''+type+'\')">+ Thêm</button><button class="btn" onclick="exportCSV(\''+type+'\')">Xuất CSV</button></div></div><div class="card table-wrap"><table class="table"><thead><tr>'+cols.map(c=>'<th>'+c+'</th>').join('')+'<th></th></tr></thead><tbody>'+rows.map((r,i)=>'<tr>'+r.map(v=>'<td>'+escHtml(v)+'</td>').join('')+'<td><button class="btn danger" onclick="removeItem(\''+type+'\','+filtered[i].id+')">Xóa</button></td></tr>').join('')+'</tbody></table>'+(rows.length?'':'<div class="empty">Không có dữ liệu</div>')+'</div>'}
function escHtml(v){return String(v??'').startsWith('<')?v:esc(v)}
function pos(){return '<div class="grid" style="grid-template-columns:1.5fr 1fr"><div class="card"><div class="toolbar"><input class="input" id="posq" placeholder="Tìm sản phẩm / SKU..." oninput="renderPOS()"></div><div class="grid cards">'+db.products.map(p=>'<div class="card" style="cursor:pointer" onclick="addCart('+p.id+')"><b>'+esc(p.name)+'</b><p class="muted">'+p.sku+' · Còn '+p.stock+'</p><strong>'+money(p.price)+'</strong></div>').join('')+'</div></div><div class="card"><h3>Giỏ hàng</h3>'+ (cart.length?cart.map((i,k)=>'<div style="display:flex;justify-content:space-between;border-bottom:1px solid #eee;padding:10px 0"><span>'+esc(i.name)+' × '+i.qty+'<br><small>'+money(i.price*i.qty)+'</small></span><button class="btn danger" onclick="cart.splice('+k+',1);renderPOS()">×</button></div>').join(''):'<div class="empty">Chưa có sản phẩm</div>')+'<hr><div style="display:flex;justify-content:space-between;font-size:20px"><b>Tổng</b><b>'+money(sum(cart.map(i=>i.price*i.qty)))+'</b></div><button class="btn primary" style="width:100%;margin-top:14px" '+(!cart.length?'disabled':'')+' onclick="checkout()">Thanh toán</button></div></div>'}
function renderPOS(){let q=document.getElementById('posq')?.value||'';let el=document.querySelector('.content');if(!el)return;el.innerHTML=pos().replace(/db\.products\.map/g,'db.products.filter(p=>JSON.stringify(p).toLowerCase().includes('+JSON.stringify(q.toLowerCase())+')).map')}
function render(){if(page==='dashboard')return dashboard();if(page==='pos')return pos();if(['products','customers','suppliers','orders','expenses'].includes(page))return tablePage(page);if(page==='inventory')return inventory();if(page==='reports')return reports();if(page==='debts')return debts();if(page==='purchases')return purchases();if(page==='settings')return settings()}
function inventory(){return '<div class="card"><h3>Biến động tồn kho</h3><div class="table-wrap"><table class="table"><thead><tr><th>Sản phẩm</th><th>Tồn</th><th>Tối thiểu</th><th>Giá trị</th><th>Trạng thái</th></tr></thead><tbody>'+db.products.map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+p.stock+'</td><td>'+p.min+'</td><td>'+money(p.stock*p.cost)+'</td><td><span class="badge '+(p.stock<=p.min?'red':'green')+'">'+(p.stock<=p.min?'Cần nhập':'Ổn định')+'</span></td></tr>').join('')+'</tbody></table></div></div>'}
function reports(){let r=revenue(),c=cost(),e=sum(db.expenses.map(x=>x.amount));return '<div class="grid stats"><div class="card"><div class="stat-label">Doanh thu</div><div class="stat-value">'+money(r)+'</div></div><div class="card"><div class="stat-label">Giá vốn</div><div class="stat-value">'+money(c)+'</div></div><div class="card"><div class="stat-label">Chi phí</div><div class="stat-value">'+money(e)+'</div></div><div class="card"><div class="stat-label">Lợi nhuận</div><div class="stat-value">'+money(r-c-e)+'</div></div></div><div class="card" style="margin-top:16px"><h3>Sản phẩm bán chạy</h3>'+db.products.map(p=>{let q=sum(db.orders.flatMap(o=>o.items||[]).filter(i=>i.productId===p.id).map(i=>i.qty));return '<p>'+esc(p.name)+' <b>'+q+'</b> sản phẩm</p>'}).join('')+'</div>'}
function debts(){return '<div class="card"><h3>Công nợ khách hàng</h3><table class="table"><thead><tr><th>Khách hàng</th><th>Điện thoại</th><th>Công nợ</th><th></th></tr></thead><tbody>'+db.customers.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+c.phone+'</td><td>'+money(c.debt)+'</td><td><button class="btn" onclick="payDebt('+c.id+')">Thu tiền</button></td></tr>').join('')+'</tbody></table></div>'}
function purchases(){return '<div class="card"><div class="toolbar"><div><h3>Nhập hàng</h3><p class="muted">Tạo phiếu nhập để tăng tồn kho và ghi nhận giá vốn.</p></div><button class="btn primary" onclick="openPurchase()">+ Nhập hàng</button></div><div class="empty">Chưa có phiếu nhập được lưu.</div></div>'}
function settings(){return '<div class="grid cards"><div class="card"><h3>Cửa hàng</h3><p class="muted">TNM Sales Manager</p><button class="btn" onclick="toast(\'Đã lưu cấu hình\')">Lưu cấu hình</button></div><div class="card"><h3>Sao lưu</h3><p class="muted">Xuất toàn bộ dữ liệu JSON.</p><button class="btn primary" onclick="backup()">Tải bản sao lưu</button><input type="file" id="restore" accept=".json" style="display:none" onchange="restore(this)"><button class="btn" onclick="document.getElementById(\'restore\').click()">Khôi phục</button></div><div class="card"><h3>Dữ liệu mẫu</h3><p class="muted">Khôi phục dữ liệu demo ban đầu.</p><button class="btn danger" onclick="resetData()">Reset dữ liệu</button></div></div>'}
function renderRefresh(){modal=null;layout()}
function openAdd(type){modal={type};layout()}
function renderModal(){let t=modal.type;if(t==='products')return modalForm('Thêm sản phẩm',['sku','name','cat','price','cost','stock','min']);if(t==='customers')return modalForm('Thêm khách hàng',['name','phone','address','debt']);if(t==='suppliers')return modalForm('Thêm nhà cung cấp',['name','phone','address']);if(t==='expenses')return modalForm('Thêm chi phí',['type','amount','date','note']);return ''}
function modalForm(title,fields){let labels={sku:'SKU',name:'Tên',cat:'Danh mục',price:'Giá bán',cost:'Giá vốn',stock:'Tồn kho',min:'Tồn tối thiểu',phone:'Điện thoại',address:'Địa chỉ',debt:'Công nợ',type:'Loại chi phí',amount:'Số tiền',date:'Ngày',note:'Ghi chú'};return '<div class="modal-bg" onclick="if(event.target===this){modal=null;layout()}"><div class="modal"><h2>'+title+'</h2><form class="form" onsubmit="saveForm(event,\''+modal.type+'\')">'+fields.map(f=>'<div class="field"><label>'+labels[f]+'</label><input name="'+f+'" '+(f==='date'?'type="date"':'type="'+(['price','cost','stock','min','debt','amount'].includes(f)?'number':'text')+'"')+' required></div>').join('')+'</form><div class="modal-actions"><button class="btn" onclick="modal=null;layout()">Hủy</button><button class="btn primary" onclick="this.closest(\'.modal\').querySelector(\'form\').requestSubmit()">Lưu</button></div></div></div>'}
function saveForm(e,type){e.preventDefault();let o=Object.fromEntries(new FormData(e));for(const k in o)if(['price','cost','stock','min','debt','amount'].includes(k))o[k]=Number(o[k]);o.id=Date.now();if(type==='products')db.products.push(o);else if(type==='customers')db.customers.push(o);else if(type==='suppliers')db.suppliers.push(o);else if(type==='expenses')db.expenses.push(o);save();toast('Đã thêm dữ liệu');modal=null;layout()}
function removeItem(type,id){if(!confirm('Xóa mục này?'))return;db[type]=db[type].filter(x=>x.id!=id);save();layout();toast('Đã xóa')}
function addCart(id){let p=db.products.find(x=>x.id===id);let x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:p.price,qty:1});renderPOS()}
function checkout(){let total=sum(cart.map(x=>x.price*x.qty));cart.forEach(i=>{let p=db.products.find(p=>p.id===i.id);p.stock=Math.max(0,p.stock-i.qty)});db.orders.push({id:Date.now(),customer:'Khách lẻ',total,status:'Hoàn thành',payment:'Tiền mặt',date:new Date().toISOString().slice(0,10),items:cart.map(i=>({productId:i.id,qty:i.qty,price:i.price}))});save();cart=[];toast('Thanh toán thành công');go('orders')}
function payDebt(id){let c=db.customers.find(x=>x.id===id);let n=prompt('Số tiền khách thanh toán',c.debt);if(n&&Number(n)>0){c.debt=Math.max(0,c.debt-Number(n));save();layout();toast('Đã ghi nhận thanh toán')}}
function exportCSV(type){let rows=db[type];let csv='\ufeff'+Object.keys(rows[0]||{}).join(',')+'\n'+rows.map(x=>Object.values(x).map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');download(csv,type+'.csv','text/csv')}
function backup(){download(JSON.stringify(db,null,2),'tnm-backup.json','application/json')}
function restore(input){let f=input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();layout();toast('Khôi phục thành công')}catch(e){toast('File backup không hợp lệ')}};r.readAsText(f)}
function resetData(){if(confirm('Xóa dữ liệu hiện tại và khôi phục dữ liệu mẫu?')){db=structuredClone(seed);save();layout();toast('Đã reset')}}
function download(data,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function toast(s){let d=document.createElement('div');d.className='toast';d.textContent=s;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function toggleTheme(){document.body.classList.toggle('dark');document.body.style.background=document.body.classList.contains('dark')?'#0f172a':'#f5f7fb'}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
layout();