import "./style.css";
type Enemy={x:number;y:number;hp:number;maxHp:number;alive:boolean;name:string;xp:number;xu:number};
const canvas=document.querySelector<HTMLCanvasElement>("#game")!,ctx=canvas.getContext("2d")!,hud=document.querySelector("#hud")!;
const saveKey="tnm-save-v1", world={w:2400,h:1600}, player={x:900,y:700,hp:100,maxHp:100,mp:60,maxMp:60,level:1,xp:0,xu:80,speed:180};
const enemies:Enemy[]=[{x:620,y:540,hp:35,maxHp:35,alive:true,name:"Sơn tặc",xp:18,xu:8},{x:1120,y:520,hp:45,maxHp:45,alive:true,name:"Sói hoang",xp:24,xu:12},{x:1280,y:900,hp:70,maxHp:70,alive:true,name:"Hắc y nhân",xp:45,xu:20},{x:520,y:1060,hp:120,maxHp:120,alive:true,name:"Đầu lĩnh sơn tặc",xp:100,xu:60}];
const keys=new Set<string>();const input={x:0,y:0};let last=performance.now(),cd=0,notice="Chào mừng hiệp khách!";
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener("resize",resize);resize();
function save(){localStorage.setItem(saveKey,JSON.stringify({player}))}function load(){try{const s=JSON.parse(localStorage.getItem(saveKey)||"null");if(s)Object.assign(player,s.player)}catch{}}
function d(a:{x:number;y:number},b:{x:number;y:number}){return Math.hypot(a.x-b.x,a.y-b.y)}
function level(){const n=player.level*100;if(player.xp>=n){player.xp-=n;player.level++;player.maxHp+=20;player.maxMp+=10;player.hp=player.maxHp;player.mp=player.maxMp;notice="Đột phá cấp "+player.level+"!"}}
function attack(){if(cd>0)return;cd=.45;const t=enemies.filter(e=>e.alive).sort((a,b)=>d(player,a)-d(player,b))[0];if(!t||d(player,t)>115){notice="Không có mục tiêu trong tầm đánh.";return}const dmg=12+player.level*3;t.hp-=dmg;notice="Bạn đánh "+t.name+" -"+dmg+" HP";if(t.hp<=0){t.alive=false;player.xp+=t.xp;player.xu+=t.xu;notice="Đã đánh bại "+t.name+"! +"+t.xp+" EXP, +"+t.xu+" Xu";level();setTimeout(()=>{t.hp=t.maxHp;t.alive=true},7000)}save()}
function update(dt:number){let x=input.x,y=input.y;if(keys.has("w")||keys.has("arrowup"))y--;if(keys.has("s")||keys.has("arrowdown"))y++;if(keys.has("a")||keys.has("arrowleft"))x--;if(keys.has("d")||keys.has("arrowright"))x++;const l=Math.hypot(x,y)||1;player.x=Math.max(30,Math.min(world.w-30,player.x+x/l*player.speed*dt));player.y=Math.max(30,Math.min(world.h-30,player.y+y/l*player.speed*dt));cd=Math.max(0,cd-dt)}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const cx=Math.max(0,Math.min(world.w-w,player.x-w/2)),cy=Math.max(0,Math.min(world.h-h,player.y-h/2));ctx.save();ctx.translate(-cx,-cy);ctx.fillStyle="#24351f";ctx.fillRect(0,0,world.w,world.h);ctx.strokeStyle="#36502b";for(let x=0;x<world.w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,world.h);ctx.stroke()}for(let y=0;y<world.h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(world.w,y);ctx.stroke()}ctx.fillStyle="#a78b55";ctx.fillRect(780,350,520,90);ctx.fillStyle="#6b4b2b";ctx.fillRect(820,300,440,50);ctx.fillStyle="#f0d9a0";ctx.font="22px sans-serif";ctx.fillText("Tân Thủ Thôn",950,405);
for(const e of enemies)if(e.alive){ctx.fillStyle="#762424";ctx.beginPath();ctx.arc(e.x,e.y,24,0,Math.PI*2);ctx.fill();ctx.fillStyle="#eee";ctx.font="13px sans-serif";ctx.fillText(e.name,e.x-30,e.y-34);ctx.fillStyle="#300";ctx.fillRect(e.x-25,e.y-28,50,5);ctx.fillStyle="#e44";ctx.fillRect(e.x-25,e.y-28,50*Math.max(0,e.hp/e.maxHp),5)}
ctx.fillStyle="#d1ad67";ctx.beginPath();ctx.arc(player.x,player.y,25,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17120d";ctx.font="bold 13px sans-serif";ctx.fillText("Hiệp khách",player.x-28,player.y-34);ctx.restore();hud.innerHTML='<div class="top"><b>⚔ Võ Lâm Web</b><span>Cấp '+player.level+'</span><span>Xu: '+player.xu+'</span></div><div class="bars">HP '+Math.round(player.hp)+' / '+player.maxHp+'<br>MP '+player.mp+' / '+player.maxMp+'<br>EXP '+player.xp+' / '+player.level*100+'</div><div class="notice">'+notice+'</div><div class="map">Tân Thủ Thôn<br><small>WASD / joystick · Space/J đánh</small></div>'}
function loop(t:number){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}load();addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key===" "||e.key.toLowerCase()==="j")attack()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
document.querySelector('[data-action="attack"]')?.addEventListener("pointerdown",attack);document.querySelector('[data-action="skill"]')?.addEventListener("pointerdown",()=>{if(player.mp>=10){player.mp-=10;notice="Võ công phát động!"}else notice="Hết nội lực!"});document.querySelector('[data-action="potion"]')?.addEventListener("pointerdown",()=>{player.hp=Math.min(player.maxHp,player.hp+35);notice="Đã dùng thuốc hồi phục.";save()});
const joy=document.querySelector<HTMLElement>("#joy")!;let pid=-1;joy.addEventListener("pointerdown",e=>{pid=e.pointerId;joy.setPointerCapture(pid)});joy.addEventListener("pointermove",e=>{if(e.pointerId!==pid)return;const r=joy.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;input.x=Math.max(-1,Math.min(1,(e.clientX-x)/(r.width/2)));input.y=Math.max(-1,Math.min(1,(e.clientY-y)/(r.height/2)));joy.querySelector("span")!.style.transform='translate('+input.x*38+'px,'+input.y*38+'px)'});joy.addEventListener("pointerup",()=>{pid=-1;input.x=input.y=0;joy.querySelector("span")!.style.transform="translate(0,0)"});setInterval(save,5000);requestAnimationFrame(loop);