import "./style.css";
type Enemy={x:number;y:number;hp:number;maxHp:number;alive:boolean;name:string;xp:number;xu:number;damage:number;speed:number;attackCd:number;boss?:boolean};
const canvas=document.querySelector<HTMLCanvasElement>("#game")!,ctx=canvas.getContext("2d")!,hud=document.querySelector("#hud")!;
const saveKey="tnm-save-v2",world={w:2400,h:1600},player={x:900,y:700,hp:100,maxHp:100,mp:60,maxMp:60,level:1,xp:0,xu:80,speed:180};
const inventory:Record<string,number>={"Tiểu hoàn đan":3,"Kim sang dược":2};
const enemies:Enemy[]=[
{x:620,y:540,hp:35,maxHp:35,alive:true,name:"Sơn tặc",xp:18,xu:8,damage:6,speed:55,attackCd:0},
{x:1120,y:520,hp:45,maxHp:45,alive:true,name:"Sói hoang",xp:24,xu:12,damage:8,speed:75,attackCd:0},
{x:1280,y:900,hp:70,maxHp:70,alive:true,name:"Hắc y nhân",xp:45,xu:20,damage:12,speed:45,attackCd:0},
{x:520,y:1060,hp:120,maxHp:120,alive:true,name:"Đầu lĩnh sơn tặc",xp:100,xu:60,damage:18,speed:38,attackCd:0,boss:true},
{x:1640,y:520,hp:55,maxHp:55,alive:true,name:"Đạo tặc",xp:30,xu:16,damage:9,speed:60,attackCd:0},
{x:1780,y:980,hp:85,maxHp:85,alive:true,name:"Thiết vệ",xp:55,xu:25,damage:14,speed:42,attackCd:0},
{x:420,y:720,hp:65,maxHp:65,alive:true,name:"Dã lang",xp:32,xu:15,damage:10,speed:68,attackCd:0},
{x:1980,y:1220,hp:180,maxHp:180,alive:true,name:"Hắc Phong Ma Vương",xp:180,xu:120,damage:24,speed:32,attackCd:0,boss:true}];
const npcs=[{x:1030,y:385,name:"Lý đại phu",type:"heal"},{x:1170,y:385,name:"Chưởng quỹ",type:"shop"},{x:850,y:385,name:"Tân thủ sứ",type:"quest"}];
const keys=new Set<string>(),input={x:0,y:0};let last=performance.now(),cd=0,notice="Chào mừng hiệp khách!";
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+"px";canvas.style.height=innerHeight+"px";ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener("resize",resize);resize();
function save(){localStorage.setItem(saveKey,JSON.stringify({player,inventory}))}function load(){try{const s=JSON.parse(localStorage.getItem(saveKey)||"null");if(s){Object.assign(player,s.player);Object.assign(inventory,s.inventory||{})}}catch{}}
function d(a:{x:number;y:number},b:{x:number;y:number}){return Math.hypot(a.x-b.x,a.y-b.y)}
function level(){while(player.xp>=player.level*100){player.xp-=player.level*100;player.level++;player.maxHp+=20;player.maxMp+=10;player.hp=player.maxHp;player.mp=player.maxMp;notice="Đột phá cấp "+player.level+"!"}}
function nearestEnemy(){return enemies.filter(e=>e.alive).sort((a,b)=>d(player,a)-d(player,b))[0]}
function respawn(e:Enemy){setTimeout(()=>{e.hp=e.maxHp;e.alive=true},7000)}
function reward(e:Enemy){player.xp+=e.xp;player.xu+=e.xu;notice="Đã đánh bại "+e.name+"! +"+e.xp+" EXP, +"+e.xu+" Xu";level();respawn(e)}
function attack(){if(cd>0)return;cd=.38;const t=nearestEnemy();if(!t||d(player,t)>125){notice="Không có mục tiêu trong tầm đánh.";return}const dmg=14+player.level*4;t.hp-=dmg;notice="Bạn đánh "+t.name+" -"+dmg+" HP";if(t.hp<=0){t.alive=false;reward(t)}save()}
function skill(){if(player.mp<15){notice="Hết nội lực!";return}player.mp-=15;const hit=enemies.filter(e=>e.alive&&d(player,e)<190),dmg=28+player.level*6;for(const e of hit){e.hp-=dmg;if(e.hp<=0){e.alive=false;reward(e)}}notice="☯ Phong Vân Kiếm! -"+dmg+" HP ("+hit.length+" mục tiêu)";save()}
function usePotion(){if(!(inventory["Tiểu hoàn đan"]>0)){notice="Đã hết Tiểu hoàn đan.";return}if(player.hp>=player.maxHp){notice="HP đang đầy.";return}inventory["Tiểu hoàn đan"]--;player.hp=Math.min(player.maxHp,player.hp+45);notice="Dùng Tiểu hoàn đan +45 HP";save()}
function interact(){const n=npcs.find(n=>d(player,n)<90);if(!n){notice="Hãy đến gần NPC để tương tác.";return}if(n.type==="heal"){player.hp=player.maxHp;player.mp=player.maxMp;notice=n.name+": Khí huyết và nội lực đã hồi phục!"}else if(n.type==="shop"){if(player.xu>=20){player.xu-=20;inventory["Tiểu hoàn đan"]=(inventory["Tiểu hoàn đan"]||0)+1;notice=n.name+": Mua 1 Tiểu hoàn đan với 20 Xu."}else notice=n.name+": Cần 20 Xu."}else{player.xp+=35;player.xu+=10;level();notice=n.name+": Hoàn thành nhiệm vụ Tân thủ! +35 EXP, +10 Xu"}save()}
function update(dt:number){let x=input.x,y=input.y;if(keys.has("w")||keys.has("arrowup"))y--;if(keys.has("s")||keys.has("arrowdown"))y++;if(keys.has("a")||keys.has("arrowleft"))x--;if(keys.has("d")||keys.has("arrowright"))x++;const l=Math.hypot(x,y)||1;player.x=Math.max(30,Math.min(world.w-30,player.x+x/l*player.speed*dt));player.y=Math.max(30,Math.min(world.h-30,player.y+y/l*player.speed*dt));cd=Math.max(0,cd-dt);
for(const e of enemies)if(e.alive){e.attackCd=Math.max(0,e.attackCd-dt);const dist=d(player,e);if(dist<300&&dist>55){e.x+=(player.x-e.x)/dist*e.speed*dt;e.y+=(player.y-e.y)/dist*e.speed*dt}else if(dist<=55&&e.attackCd<=0){player.hp=Math.max(0,player.hp-e.damage);e.attackCd=1.2;notice=e.name+" tấn công! -"+e.damage+" HP";if(player.hp<=0){player.x=900;player.y=700;player.hp=player.maxHp;player.mp=player.maxMp;notice="Bạn trọng thương và được đưa về Tân Thủ Thôn."}}}}
function draw(){const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const cx=Math.max(0,Math.min(world.w-w,player.x-w/2)),cy=Math.max(0,Math.min(world.h-h,player.y-h/2));ctx.save();ctx.translate(-cx,-cy);ctx.fillStyle="#24351f";ctx.fillRect(0,0,world.w,world.h);ctx.strokeStyle="#36502b";for(let x=0;x<world.w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,world.h);ctx.stroke()}for(let y=0;y<world.h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(world.w,y);ctx.stroke()}ctx.fillStyle="#a78b55";ctx.fillRect(780,350,520,90);ctx.fillStyle="#6b4b2b";ctx.fillRect(820,300,440,50);ctx.fillStyle="#f0d9a0";ctx.font="22px sans-serif";ctx.fillText("Tân Thủ Thôn",950,405);
for(const n of npcs){ctx.fillStyle="#e5c07b";ctx.fillRect(n.x-16,n.y-25,32,42);ctx.fillStyle="#fff0c2";ctx.font="13px sans-serif";ctx.fillText(n.name,n.x-38,n.y-35)}
for(const e of enemies)if(e.alive){ctx.fillStyle=e.boss?"#7d2c88":"#762424";ctx.beginPath();ctx.arc(e.x,e.y,e.boss?30:24,0,Math.PI*2);ctx.fill();ctx.fillStyle="#eee";ctx.font="13px sans-serif";ctx.fillText(e.name,e.x-38,e.y-38);ctx.fillStyle="#300";ctx.fillRect(e.x-30,e.y-31,60,5);ctx.fillStyle="#e44";ctx.fillRect(e.x-30,e.y-31,60*Math.max(0,e.hp/e.maxHp),5)}
ctx.fillStyle="#d1ad67";ctx.beginPath();ctx.arc(player.x,player.y,25,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17120d";ctx.font="bold 13px sans-serif";ctx.fillText("Hiệp khách",player.x-28,player.y-34);ctx.restore();
hud.innerHTML='<div class="top"><b>⚔ Võ Lâm Web</b><span>Cấp '+player.level+'</span><span>Xu: '+player.xu+'</span></div><div class="bars">HP '+Math.round(player.hp)+' / '+player.maxHp+'<br>MP '+Math.round(player.mp)+' / '+player.maxMp+'<br>EXP '+player.xp+' / '+player.level*100+'<hr>☯ '+(inventory["Tiểu hoàn đan"]||0)+' thuốc</div><div class="notice">'+notice+'</div><div class="map">Tân Thủ Thôn<br><small>WASD / joystick · ⚔ đánh · ☯ kỹ năng · E NPC</small></div>'}
function loop(t:number){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}load();addEventListener("keydown",e=>{const k=e.key.toLowerCase();keys.add(k);if(e.key===" "||k==="j")attack();if(k==="k")skill();if(k==="h")usePotion();if(k==="e")interact()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
document.querySelector('[data-action="attack"]')?.addEventListener("pointerdown",attack);document.querySelector('[data-action="skill"]')?.addEventListener("pointerdown",skill);document.querySelector('[data-action="potion"]')?.addEventListener("pointerdown",usePotion);document.querySelector('[data-action="npc"]')?.addEventListener("pointerdown",interact);
const joy=document.querySelector<HTMLElement>("#joy")!;let pid=-1;joy.addEventListener("pointerdown",e=>{pid=e.pointerId;joy.setPointerCapture(pid)});joy.addEventListener("pointermove",e=>{if(e.pointerId!==pid)return;const r=joy.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;input.x=Math.max(-1,Math.min(1,(e.clientX-x)/(r.width/2)));input.y=Math.max(-1,Math.min(1,(e.clientY-y)/(r.height/2)));joy.querySelector("span")!.style.transform="translate("+input.x*38+"px,"+input.y*38+"px)"});["pointerup","pointercancel"].forEach(ev=>joy.addEventListener(ev,()=>{pid=-1;input.x=input.y=0;joy.querySelector("span")!.style.transform="translate(0,0)"}));setInterval(save,5000);requestAnimationFrame(loop);